### ISSUE TITLE
error: no Auth Provider found for the name "GCP"

### ISSUE THREAD

**Issue by huyngopt1994** [TNK-Studio/lazykube#30]
After I installed kubelazy, and try to work with GKE cluster then I got this error 
<img width="1439" alt="Screen Shot 2020-11-21 at 10 59 32 AM" src="https://user-images.githubusercontent.com/17699212/99867091-11be7180-2be9-11eb-85ac-5af19a72c834.png">

**Comment by elfgzp** [comment]
@huyngopt1994 
This bug has been fixed.
Please upgrade to version 0.4.2. 🥳
