### ISSUE TITLE
建议：查看日志时选择pod内某一个容器查看

### ISSUE THREAD

**Issue by nzlov** [TNK-Studio/lazykube#39]
部署了Sidecar的pod看log不准确

**Comment by elfgzp** [comment]
#40 此功能已增加，待 `v0.7.0` 版本发布
![img1](https://tva1.sinaimg.cn/large/0081Kckwgy1gl070xdbndj31960mmjvy.jpg)
![img2](https://tva1.sinaimg.cn/large/0081Kckwgy1gl070vxkolj31940mfn2o.jpg)

**Comment by elfgzp** [comment]
@nzlov `v0.7.0` 已发布
