### ISSUE TITLE
建议：安装位置改为 /usr/local/bin

### ISSUE THREAD

**Issue by Maxwell1987** [TNK-Studio/lazykube#53]
目前安装脚本会自动安装在 /usr/bin 下，按照 linux 目前的习惯看，自行安装的软件放在 /usr/local/bin 比较好。

**Comment by elfgzp** [comment]
感谢建议，后续会将软件安装目录修改到 `/usr/local/bin` 下，不过需要兼容之前的用户，所以还是会在 `/usr/bin` 增加一个软链。

**Comment by Maxwell1987** [comment]
可以判断一下原来有就增加软链接，原来没有就不要增加了。

> 感谢建议，后续会将软件安装目录修改到 `/usr/local/bin` 下，不过需要兼容之前的用户，所以还是会在 `/usr/bin` 增加一个软链。
