### ISSUE TITLE
关于context指定namespace时，lazykube可以默认设置namespace的建议

### ISSUE THREAD

**Issue by lijingbo8119** [TNK-Studio/lazykube#58]
你好~
当前生产环境的context: namespaces is forbidden: User "***" cannot list resource "namespaces" in API group "" at the cluster scope
是否可以获得config中context中的namespace设置为lazykube中默认的namespace。否则目前我们生产环境的权限设置无法使用lazykube。

**Comment by elfgzp** [comment]
你好请更新至0.10.0版本 支持读取 kubetcl config set-context —current —namespace 中设置的默认命名空间

**Comment by lijingbo8119** [comment]
多谢
