### ISSUE TITLE
How to specify the right server and port?

### ISSUE THREAD

**Issue by zhangddjs** [TNK-Studio/lazykube#66]
![A93D6548-4B06-4515-B0EF-7944001835F8](https://github.com/TNK-Studio/lazykube/assets/30108045/8e7d6e04-1fba-473a-8c4c-d0de987ce193)
![FA3272DC-3255-4EFD-B38E-06EFECEC0CC1](https://github.com/TNK-Studio/lazykube/assets/30108045/edc1d11e-7a9b-4a83-8c17-b9373836d3b0)

as the pic shows, I have a k3s node, but the lazykube connect to 8080, which caused the connection refused. Doesn't it need to listen 6443 as default or some ports else? How can I fix this situation

**Comment by fwastring** [comment]
How did you solve this?
