### ISSUE TITLE
bug: 在某些情况下，日志会不停闪烁

### ISSUE THREAD

**Issue by KONY128** [TNK-Studio/lazykube#8]
问题描述：
日志在一些 pod 上显示异常，不停 “闪烁”
有 sidecar 的pod 均会出现这样的状况

问题触发：
有 sidecar 的 pod （包括 Istio sidecar 和 mongo sidecar）
calico 的日志

也许有用的解决方案：
也许可以通过：设定某个 pod 单独显示某个 container 的日志，来解决问题

使用环境：
Ubuntu: 18.04
Kubernetes: v1.18.0
Istio: v1.7.2
bash: zsh with oh-my-zsh
shell-software: windows-terminal
font-face: Cascadia Code PL

**Comment by elfgzp** [comment]
感谢反馈 我测试修复一下

**Comment by elfgzp** [comment]
@KONY128 
我还没在你的环境下测试 
不过我优化了一下日志的渲染的逻辑 更新到 `v0.1.1` 版本试一试
如果还是不行我就找时间在你的环境下测试

**Comment by elfgzp** [comment]
#9

**Comment by elfgzp** [comment]
#39

**Comment by elfgzp** [comment]
@KONY128 `v0.7.0` 已发布支持选择 Pod 具体容器查看日志
